import type { Driver, Vehicle, FleetStatusCount } from '@motive/shared'
import { currentRegion } from '~/composables/useRegion'
import type { RegionCode } from '~/composables/useRegion'

// ── US drivers ────────────────────────────────────────────────────────────────
const mockDriversUS: Driver[] = [
  {
    id: 'DRV-001',
    name: 'Marcus Johnson',
    initials: 'MJ',
    licenseNumber: 'CDL-TX-4821093',
    phone: '+1 (512) 555-0142',
    status: 'driving',
    vehicleId: 'VEH-001',
    currentLocation: { lat: 32.7767, lng: -96.797, city: 'Dallas', state: 'TX' },
    hos: {
      drivingRemaining: 6.5,
      onDutyRemaining: 8.0,
      drivingToday: 4.5,
      onDutyToday: 6.0,
      sleeperToday: 0,
      offDutyToday: 2.0,
      hasViolation: false,
      cycleUsed: 42.5,
      cycleRemaining: 27.5,
    },
    etaNextStop: '2:45 PM',
    currentLoad: 'LOAD-8821',
    milesDrivenToday: 287,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-002',
    name: 'Sarah Chen',
    initials: 'SC',
    licenseNumber: 'CDL-CA-7734521',
    phone: '+1 (213) 555-0198',
    status: 'driving',
    vehicleId: 'VEH-002',
    currentLocation: { lat: 34.0522, lng: -118.2437, city: 'Los Angeles', state: 'CA' },
    hos: {
      drivingRemaining: 9.0,
      onDutyRemaining: 11.5,
      drivingToday: 2.0,
      onDutyToday: 2.5,
      sleeperToday: 8.0,
      offDutyToday: 1.5,
      hasViolation: false,
      cycleUsed: 28.0,
      cycleRemaining: 42.0,
    },
    etaNextStop: '4:15 PM',
    currentLoad: 'LOAD-8834',
    milesDrivenToday: 143,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-003',
    name: 'Robert Torres',
    initials: 'RT',
    licenseNumber: 'CDL-FL-2298341',
    phone: '+1 (305) 555-0167',
    status: 'idle',
    vehicleId: 'VEH-003',
    currentLocation: { lat: 25.7617, lng: -80.1918, city: 'Miami', state: 'FL' },
    hos: {
      drivingRemaining: 11.0,
      onDutyRemaining: 14.0,
      drivingToday: 0,
      onDutyToday: 0,
      sleeperToday: 0,
      offDutyToday: 10.0,
      hasViolation: false,
      cycleUsed: 15.0,
      cycleRemaining: 55.0,
    },
    etaNextStop: undefined,
    currentLoad: undefined,
    milesDrivenToday: 0,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-004',
    name: 'Amanda Williams',
    initials: 'AW',
    licenseNumber: 'CDL-IL-5512847',
    phone: '+1 (312) 555-0223',
    status: 'driving',
    vehicleId: 'VEH-004',
    currentLocation: { lat: 41.8781, lng: -87.6298, city: 'Chicago', state: 'IL' },
    hos: {
      drivingRemaining: 1.5,
      onDutyRemaining: 2.0,
      drivingToday: 9.5,
      onDutyToday: 12.0,
      sleeperToday: 0,
      offDutyToday: 2.0,
      hasViolation: false,
      cycleUsed: 68.0,
      cycleRemaining: 2.0,
    },
    etaNextStop: '1:30 PM',
    currentLoad: 'LOAD-8819',
    milesDrivenToday: 612,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-005',
    name: 'Derek Okafor',
    initials: 'DO',
    licenseNumber: 'CDL-GA-8834129',
    phone: '+1 (404) 555-0089',
    status: 'alert',
    vehicleId: 'VEH-005',
    currentLocation: { lat: 33.749, lng: -84.388, city: 'Atlanta', state: 'GA' },
    hos: {
      drivingRemaining: 0,
      onDutyRemaining: 0,
      drivingToday: 11.0,
      onDutyToday: 14.0,
      sleeperToday: 0,
      offDutyToday: 0,
      hasViolation: true,
      cycleUsed: 70.0,
      cycleRemaining: 0,
    },
    etaNextStop: undefined,
    currentLoad: 'LOAD-8807',
    milesDrivenToday: 724,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-006',
    name: 'Lisa Nguyen',
    initials: 'LN',
    licenseNumber: 'CDL-WA-3341892',
    phone: '+1 (206) 555-0311',
    status: 'sleeper',
    vehicleId: 'VEH-006',
    currentLocation: { lat: 47.6062, lng: -122.3321, city: 'Seattle', state: 'WA' },
    hos: {
      drivingRemaining: 11.0,
      onDutyRemaining: 14.0,
      drivingToday: 0,
      onDutyToday: 0,
      sleeperToday: 6.0,
      offDutyToday: 0,
      hasViolation: false,
      cycleUsed: 52.0,
      cycleRemaining: 18.0,
    },
    etaNextStop: '6:00 AM',
    currentLoad: 'LOAD-8841',
    milesDrivenToday: 0,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-007',
    name: 'James Patel',
    initials: 'JP',
    licenseNumber: 'CDL-AZ-9921034',
    phone: '+1 (602) 555-0445',
    status: 'driving',
    vehicleId: 'VEH-007',
    currentLocation: { lat: 33.4484, lng: -112.074, city: 'Phoenix', state: 'AZ' },
    hos: {
      drivingRemaining: 7.5,
      onDutyRemaining: 9.0,
      drivingToday: 3.5,
      onDutyToday: 5.0,
      sleeperToday: 0,
      offDutyToday: 3.0,
      hasViolation: false,
      cycleUsed: 38.5,
      cycleRemaining: 31.5,
    },
    etaNextStop: '3:00 PM',
    currentLoad: 'LOAD-8852',
    milesDrivenToday: 231,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-008',
    name: 'Tanya Brooks',
    initials: 'TB',
    licenseNumber: 'CDL-NY-6678234',
    phone: '+1 (718) 555-0567',
    status: 'offline',
    vehicleId: 'VEH-008',
    currentLocation: { lat: 40.7128, lng: -74.006, city: 'New York', state: 'NY' },
    hos: {
      drivingRemaining: 11.0,
      onDutyRemaining: 14.0,
      drivingToday: 0,
      onDutyToday: 0,
      sleeperToday: 0,
      offDutyToday: 14.0,
      hasViolation: false,
      cycleUsed: 22.0,
      cycleRemaining: 48.0,
    },
    etaNextStop: undefined,
    currentLoad: undefined,
    milesDrivenToday: 0,
    lastUpdated: new Date(Date.now() - 3600000),
  },
  {
    id: 'DRV-009',
    name: 'Carlos Mendez',
    initials: 'CM',
    licenseNumber: 'CDL-TX-1123456',
    phone: '+1 (713) 555-0789',
    status: 'driving',
    vehicleId: 'VEH-009',
    currentLocation: { lat: 29.7604, lng: -95.3698, city: 'Houston', state: 'TX' },
    hos: {
      drivingRemaining: 5.0,
      onDutyRemaining: 6.5,
      drivingToday: 6.0,
      onDutyToday: 7.5,
      sleeperToday: 0,
      offDutyToday: 2.5,
      hasViolation: false,
      cycleUsed: 55.0,
      cycleRemaining: 15.0,
    },
    etaNextStop: '5:30 PM',
    currentLoad: 'LOAD-8863',
    milesDrivenToday: 389,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-010',
    name: 'Rachel Kim',
    initials: 'RK',
    licenseNumber: 'CDL-CO-4456789',
    phone: '+1 (720) 555-0234',
    status: 'idle',
    vehicleId: 'VEH-010',
    currentLocation: { lat: 39.7392, lng: -104.9903, city: 'Denver', state: 'CO' },
    hos: {
      drivingRemaining: 8.0,
      onDutyRemaining: 10.0,
      drivingToday: 3.0,
      onDutyToday: 4.0,
      sleeperToday: 0,
      offDutyToday: 4.0,
      hasViolation: false,
      cycleUsed: 31.0,
      cycleRemaining: 39.0,
    },
    etaNextStop: undefined,
    currentLoad: undefined,
    milesDrivenToday: 198,
    lastUpdated: new Date(),
  },
]

// ── MX drivers ────────────────────────────────────────────────────────────────
const mockDriversMX: Driver[] = [
  {
    id: 'DRV-MX-001',
    name: 'Carlos Fuentes',
    initials: 'CF',
    licenseNumber: 'LIC-MX-CD-48210',
    phone: '+52 (55) 5555-0142',
    status: 'driving',
    vehicleId: 'VEH-MX-001',
    currentLocation: { lat: 19.4326, lng: -99.1332, city: 'Ciudad de México', state: 'CDMX' },
    hos: {
      drivingRemaining: 6.5,
      onDutyRemaining: 8.0,
      drivingToday: 4.5,
      onDutyToday: 6.0,
      sleeperToday: 0,
      offDutyToday: 2.0,
      hasViolation: false,
      cycleUsed: 42.5,
      cycleRemaining: 27.5,
    },
    etaNextStop: '2:45 PM',
    currentLoad: 'CARGA-8821',
    milesDrivenToday: 287,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-MX-002',
    name: 'Ana Martínez',
    initials: 'AM',
    licenseNumber: 'LIC-MX-GJ-77345',
    phone: '+52 (33) 5555-0198',
    status: 'driving',
    vehicleId: 'VEH-MX-002',
    currentLocation: { lat: 20.6597, lng: -103.3496, city: 'Guadalajara', state: 'JAL' },
    hos: {
      drivingRemaining: 9.0,
      onDutyRemaining: 11.5,
      drivingToday: 2.0,
      onDutyToday: 2.5,
      sleeperToday: 8.0,
      offDutyToday: 1.5,
      hasViolation: false,
      cycleUsed: 28.0,
      cycleRemaining: 42.0,
    },
    etaNextStop: '4:15 PM',
    currentLoad: 'CARGA-8834',
    milesDrivenToday: 143,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-MX-003',
    name: 'Manuel Reyes',
    initials: 'MR',
    licenseNumber: 'LIC-MX-NL-22983',
    phone: '+52 (81) 5555-0167',
    status: 'idle',
    vehicleId: 'VEH-MX-003',
    currentLocation: { lat: 25.6866, lng: -100.3161, city: 'Monterrey', state: 'NL' },
    hos: {
      drivingRemaining: 11.0,
      onDutyRemaining: 14.0,
      drivingToday: 0,
      onDutyToday: 0,
      sleeperToday: 0,
      offDutyToday: 10.0,
      hasViolation: false,
      cycleUsed: 15.0,
      cycleRemaining: 55.0,
    },
    etaNextStop: undefined,
    currentLoad: undefined,
    milesDrivenToday: 0,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-MX-004',
    name: 'Isabella Vargas',
    initials: 'IV',
    licenseNumber: 'LIC-MX-PU-55128',
    phone: '+52 (222) 5555-0223',
    status: 'driving',
    vehicleId: 'VEH-MX-004',
    currentLocation: { lat: 19.0414, lng: -98.2063, city: 'Puebla', state: 'PUE' },
    hos: {
      drivingRemaining: 1.5,
      onDutyRemaining: 2.0,
      drivingToday: 9.5,
      onDutyToday: 12.0,
      sleeperToday: 0,
      offDutyToday: 2.0,
      hasViolation: false,
      cycleUsed: 68.0,
      cycleRemaining: 2.0,
    },
    etaNextStop: '1:30 PM',
    currentLoad: 'CARGA-8819',
    milesDrivenToday: 612,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-MX-005',
    name: 'Diego Hernández',
    initials: 'DH',
    licenseNumber: 'LIC-MX-BC-88341',
    phone: '+52 (664) 5555-0089',
    status: 'alert',
    vehicleId: 'VEH-MX-005',
    currentLocation: { lat: 32.5149, lng: -117.0382, city: 'Tijuana', state: 'BC' },
    hos: {
      drivingRemaining: 0,
      onDutyRemaining: 0,
      drivingToday: 11.0,
      onDutyToday: 14.0,
      sleeperToday: 0,
      offDutyToday: 0,
      hasViolation: true,
      cycleUsed: 70.0,
      cycleRemaining: 0,
    },
    etaNextStop: undefined,
    currentLoad: 'CARGA-8807',
    milesDrivenToday: 724,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-MX-006',
    name: 'Sofía López',
    initials: 'SL',
    licenseNumber: 'LIC-MX-YUC-33418',
    phone: '+52 (999) 5555-0311',
    status: 'sleeper',
    vehicleId: 'VEH-MX-006',
    currentLocation: { lat: 20.9674, lng: -89.5926, city: 'Mérida', state: 'YUC' },
    hos: {
      drivingRemaining: 11.0,
      onDutyRemaining: 14.0,
      drivingToday: 0,
      onDutyToday: 0,
      sleeperToday: 6.0,
      offDutyToday: 0,
      hasViolation: false,
      cycleUsed: 52.0,
      cycleRemaining: 18.0,
    },
    etaNextStop: '6:00 AM',
    currentLoad: 'CARGA-8841',
    milesDrivenToday: 0,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-MX-007',
    name: 'Ricardo Castillo',
    initials: 'RC',
    licenseNumber: 'LIC-MX-QRO-99210',
    phone: '+52 (442) 5555-0445',
    status: 'driving',
    vehicleId: 'VEH-MX-007',
    currentLocation: { lat: 20.5888, lng: -100.3899, city: 'Querétaro', state: 'QRO' },
    hos: {
      drivingRemaining: 7.5,
      onDutyRemaining: 9.0,
      drivingToday: 3.5,
      onDutyToday: 5.0,
      sleeperToday: 0,
      offDutyToday: 3.0,
      hasViolation: false,
      cycleUsed: 38.5,
      cycleRemaining: 31.5,
    },
    etaNextStop: '3:00 PM',
    currentLoad: 'CARGA-8852',
    milesDrivenToday: 231,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-MX-008',
    name: 'Carmen Ortega',
    initials: 'CO',
    licenseNumber: 'LIC-MX-CHIH-66782',
    phone: '+52 (614) 5555-0567',
    status: 'offline',
    vehicleId: 'VEH-MX-008',
    currentLocation: { lat: 28.6353, lng: -106.0889, city: 'Chihuahua', state: 'CHIH' },
    hos: {
      drivingRemaining: 11.0,
      onDutyRemaining: 14.0,
      drivingToday: 0,
      onDutyToday: 0,
      sleeperToday: 0,
      offDutyToday: 14.0,
      hasViolation: false,
      cycleUsed: 22.0,
      cycleRemaining: 48.0,
    },
    etaNextStop: undefined,
    currentLoad: undefined,
    milesDrivenToday: 0,
    lastUpdated: new Date(Date.now() - 3600000),
  },
  {
    id: 'DRV-MX-009',
    name: 'Javier Guzmán',
    initials: 'JG',
    licenseNumber: 'LIC-MX-GTO-11234',
    phone: '+52 (477) 5555-0789',
    status: 'driving',
    vehicleId: 'VEH-MX-009',
    currentLocation: { lat: 21.1221, lng: -101.6834, city: 'León', state: 'GTO' },
    hos: {
      drivingRemaining: 5.0,
      onDutyRemaining: 6.5,
      drivingToday: 6.0,
      onDutyToday: 7.5,
      sleeperToday: 0,
      offDutyToday: 2.5,
      hasViolation: false,
      cycleUsed: 55.0,
      cycleRemaining: 15.0,
    },
    etaNextStop: '5:30 PM',
    currentLoad: 'CARGA-8863',
    milesDrivenToday: 389,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-MX-010',
    name: 'Valentina Cruz',
    initials: 'VC',
    licenseNumber: 'LIC-MX-COAH-44567',
    phone: '+52 (844) 5555-0234',
    status: 'idle',
    vehicleId: 'VEH-MX-010',
    currentLocation: { lat: 25.4232, lng: -100.9936, city: 'Saltillo', state: 'COAH' },
    hos: {
      drivingRemaining: 8.0,
      onDutyRemaining: 10.0,
      drivingToday: 3.0,
      onDutyToday: 4.0,
      sleeperToday: 0,
      offDutyToday: 4.0,
      hasViolation: false,
      cycleUsed: 31.0,
      cycleRemaining: 39.0,
    },
    etaNextStop: undefined,
    currentLoad: undefined,
    milesDrivenToday: 198,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-MX-011',
    name: 'Omar Vega',
    initials: 'OV',
    licenseNumber: 'LIC-MX-VER-30211',
    phone: '+52 (229) 5555-0110',
    status: 'driving',
    vehicleId: 'VEH-MX-011',
    currentLocation: { lat: 19.1738, lng: -96.1342, city: 'Veracruz', state: 'VER' },
    hos: {
      drivingRemaining: 5.5,
      onDutyRemaining: 7.0,
      drivingToday: 5.5,
      onDutyToday: 7.0,
      sleeperToday: 0,
      offDutyToday: 1.0,
      hasViolation: false,
      cycleUsed: 49.0,
      cycleRemaining: 21.0,
    },
    etaNextStop: '6:00 PM',
    currentLoad: 'CARGA-9101',
    milesDrivenToday: 341,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-MX-012',
    name: 'Patricia Ramos',
    initials: 'PR',
    licenseNumber: 'LIC-MX-OAX-51290',
    phone: '+52 (951) 5555-0122',
    status: 'driving',
    vehicleId: 'VEH-MX-012',
    currentLocation: { lat: 17.0669, lng: -96.7203, city: 'Oaxaca', state: 'OAX' },
    hos: {
      drivingRemaining: 8.0,
      onDutyRemaining: 10.5,
      drivingToday: 3.0,
      onDutyToday: 3.5,
      sleeperToday: 0,
      offDutyToday: 4.5,
      hasViolation: false,
      cycleUsed: 35.0,
      cycleRemaining: 35.0,
    },
    etaNextStop: '5:15 PM',
    currentLoad: 'CARGA-9112',
    milesDrivenToday: 194,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-MX-013',
    name: 'Héctor Morales',
    initials: 'HM',
    licenseNumber: 'LIC-MX-SLP-77041',
    phone: '+52 (444) 5555-0133',
    status: 'idle',
    vehicleId: 'VEH-MX-013',
    currentLocation: { lat: 22.1565, lng: -100.9855, city: 'San Luis Potosí', state: 'SLP' },
    hos: {
      drivingRemaining: 10.0,
      onDutyRemaining: 13.0,
      drivingToday: 1.0,
      onDutyToday: 1.0,
      sleeperToday: 0,
      offDutyToday: 7.0,
      hasViolation: false,
      cycleUsed: 18.0,
      cycleRemaining: 52.0,
    },
    etaNextStop: undefined,
    currentLoad: undefined,
    milesDrivenToday: 62,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-MX-014',
    name: 'Liliana Torres',
    initials: 'LT',
    licenseNumber: 'LIC-MX-COAH-23814',
    phone: '+52 (871) 5555-0144',
    status: 'driving',
    vehicleId: 'VEH-MX-014',
    currentLocation: { lat: 25.5428, lng: -103.4068, city: 'Torreón', state: 'COAH' },
    hos: {
      drivingRemaining: 4.0,
      onDutyRemaining: 5.5,
      drivingToday: 7.0,
      onDutyToday: 8.5,
      sleeperToday: 0,
      offDutyToday: 1.5,
      hasViolation: false,
      cycleUsed: 60.0,
      cycleRemaining: 10.0,
    },
    etaNextStop: '4:45 PM',
    currentLoad: 'CARGA-9141',
    milesDrivenToday: 453,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-MX-015',
    name: 'Gabriel Navarro',
    initials: 'GN',
    licenseNumber: 'LIC-MX-SIN-60523',
    phone: '+52 (669) 5555-0155',
    status: 'driving',
    vehicleId: 'VEH-MX-015',
    currentLocation: { lat: 23.2494, lng: -106.4111, city: 'Mazatlán', state: 'SIN' },
    hos: {
      drivingRemaining: 6.0,
      onDutyRemaining: 8.0,
      drivingToday: 5.0,
      onDutyToday: 6.0,
      sleeperToday: 0,
      offDutyToday: 2.0,
      hasViolation: false,
      cycleUsed: 44.0,
      cycleRemaining: 26.0,
    },
    etaNextStop: '7:00 PM',
    currentLoad: 'CARGA-9155',
    milesDrivenToday: 318,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-MX-016',
    name: 'Claudia Mendoza',
    initials: 'CM',
    licenseNumber: 'LIC-MX-SON-88167',
    phone: '+52 (662) 5555-0166',
    status: 'driving',
    vehicleId: 'VEH-MX-016',
    currentLocation: { lat: 29.0729, lng: -110.9559, city: 'Hermosillo', state: 'SON' },
    hos: {
      drivingRemaining: 7.0,
      onDutyRemaining: 9.0,
      drivingToday: 4.0,
      onDutyToday: 5.0,
      sleeperToday: 0,
      offDutyToday: 3.0,
      hasViolation: false,
      cycleUsed: 41.0,
      cycleRemaining: 29.0,
    },
    etaNextStop: '3:30 PM',
    currentLoad: 'CARGA-9166',
    milesDrivenToday: 267,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-MX-017',
    name: 'Rodrigo Peña',
    initials: 'RP',
    licenseNumber: 'LIC-MX-GRO-44712',
    phone: '+52 (744) 5555-0177',
    status: 'offline',
    vehicleId: 'VEH-MX-017',
    currentLocation: { lat: 16.8531, lng: -99.8237, city: 'Acapulco', state: 'GRO' },
    hos: {
      drivingRemaining: 11.0,
      onDutyRemaining: 14.0,
      drivingToday: 0,
      onDutyToday: 0,
      sleeperToday: 0,
      offDutyToday: 14.0,
      hasViolation: false,
      cycleUsed: 20.0,
      cycleRemaining: 50.0,
    },
    etaNextStop: undefined,
    currentLoad: undefined,
    milesDrivenToday: 0,
    lastUpdated: new Date(Date.now() - 7200000),
  },
  {
    id: 'DRV-MX-018',
    name: 'Fernanda Ruiz',
    initials: 'FR',
    licenseNumber: 'LIC-MX-QROO-19038',
    phone: '+52 (998) 5555-0188',
    status: 'driving',
    vehicleId: 'VEH-MX-018',
    currentLocation: { lat: 21.1619, lng: -86.8515, city: 'Cancún', state: 'QROO' },
    hos: {
      drivingRemaining: 9.5,
      onDutyRemaining: 12.0,
      drivingToday: 1.5,
      onDutyToday: 2.0,
      sleeperToday: 0,
      offDutyToday: 6.0,
      hasViolation: false,
      cycleUsed: 26.0,
      cycleRemaining: 44.0,
    },
    etaNextStop: '4:00 PM',
    currentLoad: 'CARGA-9188',
    milesDrivenToday: 97,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-MX-019',
    name: 'Ignacio Sandoval',
    initials: 'IS',
    licenseNumber: 'LIC-MX-MICH-65503',
    phone: '+52 (443) 5555-0199',
    status: 'idle',
    vehicleId: 'VEH-MX-019',
    currentLocation: { lat: 19.706, lng: -101.195, city: 'Morelia', state: 'MICH' },
    hos: {
      drivingRemaining: 9.0,
      onDutyRemaining: 12.0,
      drivingToday: 2.0,
      onDutyToday: 2.0,
      sleeperToday: 0,
      offDutyToday: 6.0,
      hasViolation: false,
      cycleUsed: 29.0,
      cycleRemaining: 41.0,
    },
    etaNextStop: undefined,
    currentLoad: undefined,
    milesDrivenToday: 134,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-MX-020',
    name: 'Daniela Fuentes',
    initials: 'DF',
    licenseNumber: 'LIC-MX-TAMPS-82290',
    phone: '+52 (833) 5555-0200',
    status: 'driving',
    vehicleId: 'VEH-MX-020',
    currentLocation: { lat: 22.2331, lng: -97.8612, city: 'Tampico', state: 'TAMPS' },
    hos: {
      drivingRemaining: 6.5,
      onDutyRemaining: 8.0,
      drivingToday: 4.5,
      onDutyToday: 6.0,
      sleeperToday: 0,
      offDutyToday: 2.0,
      hasViolation: false,
      cycleUsed: 45.0,
      cycleRemaining: 25.0,
    },
    etaNextStop: '5:00 PM',
    currentLoad: 'CARGA-9200',
    milesDrivenToday: 276,
    lastUpdated: new Date(),
  },
]

// ── UK drivers ────────────────────────────────────────────────────────────────
const mockDriversUK: Driver[] = [
  {
    id: 'DRV-UK-001',
    name: 'James Whitfield',
    initials: 'JW',
    licenseNumber: 'DVL-UK-LO-48210',
    phone: '+44 (20) 5555-0142',
    status: 'driving',
    vehicleId: 'VEH-UK-001',
    currentLocation: { lat: 51.5074, lng: -0.1278, city: 'London', state: 'ENG' },
    hos: {
      drivingRemaining: 6.5,
      onDutyRemaining: 8.0,
      drivingToday: 4.5,
      onDutyToday: 6.0,
      sleeperToday: 0,
      offDutyToday: 2.0,
      hasViolation: false,
      cycleUsed: 42.5,
      cycleRemaining: 27.5,
    },
    etaNextStop: '2:45 PM',
    currentLoad: 'LOAD-UK-8821',
    milesDrivenToday: 187,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-UK-002',
    name: 'Emily Clarke',
    initials: 'EC',
    licenseNumber: 'DVL-UK-GM-77345',
    phone: '+44 (161) 5555-0198',
    status: 'driving',
    vehicleId: 'VEH-UK-002',
    currentLocation: { lat: 53.4808, lng: -2.2426, city: 'Manchester', state: 'ENG' },
    hos: {
      drivingRemaining: 9.0,
      onDutyRemaining: 11.5,
      drivingToday: 2.0,
      onDutyToday: 2.5,
      sleeperToday: 8.0,
      offDutyToday: 1.5,
      hasViolation: false,
      cycleUsed: 28.0,
      cycleRemaining: 42.0,
    },
    etaNextStop: '4:15 PM',
    currentLoad: 'LOAD-UK-8834',
    milesDrivenToday: 112,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-UK-003',
    name: 'Oliver Murphy',
    initials: 'OM',
    licenseNumber: 'DVL-UK-WM-22983',
    phone: '+44 (121) 5555-0167',
    status: 'idle',
    vehicleId: 'VEH-UK-003',
    currentLocation: { lat: 52.4862, lng: -1.8904, city: 'Birmingham', state: 'ENG' },
    hos: {
      drivingRemaining: 11.0,
      onDutyRemaining: 14.0,
      drivingToday: 0,
      onDutyToday: 0,
      sleeperToday: 0,
      offDutyToday: 10.0,
      hasViolation: false,
      cycleUsed: 15.0,
      cycleRemaining: 55.0,
    },
    etaNextStop: undefined,
    currentLoad: undefined,
    milesDrivenToday: 0,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-UK-004',
    name: 'Charlotte Davies',
    initials: 'CD',
    licenseNumber: 'DVL-UK-YK-55128',
    phone: '+44 (113) 5555-0223',
    status: 'driving',
    vehicleId: 'VEH-UK-004',
    currentLocation: { lat: 53.8008, lng: -1.5491, city: 'Leeds', state: 'ENG' },
    hos: {
      drivingRemaining: 1.5,
      onDutyRemaining: 2.0,
      drivingToday: 9.5,
      onDutyToday: 12.0,
      sleeperToday: 0,
      offDutyToday: 2.0,
      hasViolation: false,
      cycleUsed: 68.0,
      cycleRemaining: 2.0,
    },
    etaNextStop: '1:30 PM',
    currentLoad: 'LOAD-UK-8819',
    milesDrivenToday: 421,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-UK-005',
    name: 'Liam Robertson',
    initials: 'LR',
    licenseNumber: 'DVL-UK-SC-88341',
    phone: '+44 (141) 5555-0089',
    status: 'alert',
    vehicleId: 'VEH-UK-005',
    currentLocation: { lat: 55.8642, lng: -4.2518, city: 'Glasgow', state: 'SCO' },
    hos: {
      drivingRemaining: 0,
      onDutyRemaining: 0,
      drivingToday: 11.0,
      onDutyToday: 14.0,
      sleeperToday: 0,
      offDutyToday: 0,
      hasViolation: true,
      cycleUsed: 70.0,
      cycleRemaining: 0,
    },
    etaNextStop: undefined,
    currentLoad: 'LOAD-UK-8807',
    milesDrivenToday: 531,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-UK-006',
    name: 'Sophie Blackwood',
    initials: 'SB',
    licenseNumber: 'DVL-UK-SC-33418',
    phone: '+44 (131) 5555-0311',
    status: 'sleeper',
    vehicleId: 'VEH-UK-006',
    currentLocation: { lat: 55.9533, lng: -3.1883, city: 'Edinburgh', state: 'SCO' },
    hos: {
      drivingRemaining: 11.0,
      onDutyRemaining: 14.0,
      drivingToday: 0,
      onDutyToday: 0,
      sleeperToday: 6.0,
      offDutyToday: 0,
      hasViolation: false,
      cycleUsed: 52.0,
      cycleRemaining: 18.0,
    },
    etaNextStop: '6:00 AM',
    currentLoad: 'LOAD-UK-8841',
    milesDrivenToday: 0,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-UK-007',
    name: 'Henry Thornton',
    initials: 'HT',
    licenseNumber: 'DVL-UK-AV-99210',
    phone: '+44 (117) 5555-0445',
    status: 'driving',
    vehicleId: 'VEH-UK-007',
    currentLocation: { lat: 51.4545, lng: -2.5879, city: 'Bristol', state: 'ENG' },
    hos: {
      drivingRemaining: 7.5,
      onDutyRemaining: 9.0,
      drivingToday: 3.5,
      onDutyToday: 5.0,
      sleeperToday: 0,
      offDutyToday: 3.0,
      hasViolation: false,
      cycleUsed: 38.5,
      cycleRemaining: 31.5,
    },
    etaNextStop: '3:00 PM',
    currentLoad: 'LOAD-UK-8852',
    milesDrivenToday: 198,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-UK-008',
    name: 'Emma Pearson',
    initials: 'EP',
    licenseNumber: 'DVL-UK-MW-66782',
    phone: '+44 (151) 5555-0567',
    status: 'offline',
    vehicleId: 'VEH-UK-008',
    currentLocation: { lat: 53.4084, lng: -2.9916, city: 'Liverpool', state: 'ENG' },
    hos: {
      drivingRemaining: 11.0,
      onDutyRemaining: 14.0,
      drivingToday: 0,
      onDutyToday: 0,
      sleeperToday: 0,
      offDutyToday: 14.0,
      hasViolation: false,
      cycleUsed: 22.0,
      cycleRemaining: 48.0,
    },
    etaNextStop: undefined,
    currentLoad: undefined,
    milesDrivenToday: 0,
    lastUpdated: new Date(Date.now() - 3600000),
  },
  {
    id: 'DRV-UK-009',
    name: 'William Foster',
    initials: 'WF',
    licenseNumber: 'DVL-UK-SY-11234',
    phone: '+44 (114) 5555-0789',
    status: 'driving',
    vehicleId: 'VEH-UK-009',
    currentLocation: { lat: 53.3811, lng: -1.4701, city: 'Sheffield', state: 'ENG' },
    hos: {
      drivingRemaining: 5.0,
      onDutyRemaining: 6.5,
      drivingToday: 6.0,
      onDutyToday: 7.5,
      sleeperToday: 0,
      offDutyToday: 2.5,
      hasViolation: false,
      cycleUsed: 55.0,
      cycleRemaining: 15.0,
    },
    etaNextStop: '5:30 PM',
    currentLoad: 'LOAD-UK-8863',
    milesDrivenToday: 312,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-UK-010',
    name: 'Grace Hammond',
    initials: 'GH',
    licenseNumber: 'DVL-UK-WA-44567',
    phone: '+44 (29) 5555-0234',
    status: 'idle',
    vehicleId: 'VEH-UK-010',
    currentLocation: { lat: 51.4816, lng: -3.1791, city: 'Cardiff', state: 'WAL' },
    hos: {
      drivingRemaining: 8.0,
      onDutyRemaining: 10.0,
      drivingToday: 3.0,
      onDutyToday: 4.0,
      sleeperToday: 0,
      offDutyToday: 4.0,
      hasViolation: false,
      cycleUsed: 31.0,
      cycleRemaining: 39.0,
    },
    etaNextStop: undefined,
    currentLoad: undefined,
    milesDrivenToday: 163,
    lastUpdated: new Date(),
  },
]

// ── Vehicle factory ───────────────────────────────────────────────────────────
function buildVehicles(
  drivers: Driver[],
  makes: string[],
  models: string[],
  plates: (i: number) => string,
): Vehicle[] {
  return drivers.map((d, i) => ({
    id: d.vehicleId,
    make: makes[i % makes.length]!,
    model: models[i % models.length]!,
    year: 2020 + (i % 4),
    vin: `1FUJGBDV${String(i + 1).padStart(2, '0')}LJK${String(10000 + i * 1234)}`,
    licensePlate: plates(i),
    status: d.status === 'driving' ? 'active' : d.status === 'offline' ? 'offline' : 'idle',
    mileage: 85000 + i * 12500,
    fuelLevel: 20 + ((i * 17) % 80),
    driverId: d.id,
    lastInspection: new Date(Date.now() - (i + 1) * 7 * 24 * 3600000),
  }))
}

const mockVehiclesUS = buildVehicles(
  mockDriversUS,
  ['Freightliner', 'Kenworth', 'Peterbilt', 'Volvo', 'Mack'],
  ['Cascadia', 'T680', '579', 'VNL 860', 'Anthem'],
  (i) =>
    `${['TX', 'CA', 'FL', 'IL', 'GA', 'WA', 'AZ', 'NY', 'TX', 'CO'][i]}-${String(100000 + i * 12345).slice(0, 6)}`,
)

const mockVehiclesMX = buildVehicles(
  mockDriversMX,
  ['Kenworth', 'International', 'Peterbilt', 'Freightliner', 'Volvo'],
  ['T800', 'LT 625', '389', 'Cascadia', 'FH'],
  (i) =>
    `${['CDMX', 'JA', 'NL', 'PU', 'BC', 'YU', 'QR', 'CH', 'GT', 'CO'][i]}-${String(100 + i * 123).slice(0, 3)}-${String(100 + i * 321).slice(0, 3)}`,
)

const mockVehiclesUK = buildVehicles(
  mockDriversUK,
  ['DAF', 'Scania', 'Volvo', 'MAN', 'Mercedes-Benz'],
  ['XF', 'R 500', 'FH', 'TGX', 'Actros'],
  (i) => {
    const letters = ['AB', 'CD', 'EF', 'GH', 'HJ', 'KL', 'MN', 'OP', 'RS', 'TU']
    return `${letters[i]} ${String(10 + i * 7).slice(0, 2)} ${letters[(i + 3) % 10]}`
  },
)

// ── Region map ────────────────────────────────────────────────────────────────
const driversByRegion: Record<RegionCode, Driver[]> = {
  us: mockDriversUS,
  mx: mockDriversMX,
  uk: mockDriversUK,
}

const vehiclesByRegion: Record<RegionCode, Vehicle[]> = {
  us: mockVehiclesUS,
  mx: mockVehiclesMX,
  uk: mockVehiclesUK,
}

export function useFleetData() {
  const drivers = computed<Driver[]>(() => driversByRegion[currentRegion.value])
  const vehicles = computed<Vehicle[]>(() => vehiclesByRegion[currentRegion.value])
  const loading = ref(false)

  const fleetStatus = computed<FleetStatusCount>(() => {
    const counts = { driving: 0, idle: 0, offline: 0, alert: 0, total: drivers.value.length }
    for (const d of drivers.value) {
      if (d.status === 'driving') counts.driving++
      else if (d.status === 'idle' || d.status === 'sleeper') counts.idle++
      else if (d.status === 'offline') counts.offline++
      else if (d.status === 'alert') counts.alert++
    }
    return counts
  })

  async function refresh() {
    loading.value = true
    await new Promise((r) => setTimeout(r, 800))
    loading.value = false
  }

  return { drivers, vehicles, fleetStatus, loading, refresh }
}
