import type { Driver, Vehicle, FleetStatusCount } from '@motive/shared'

const mockDrivers: Driver[] = [
  {
    id: 'DRV-001',
    name: 'Marcus Johnson',
    initials: 'MJ',
    licenseNumber: 'CDL-TX-4821093',
    phone: '+1 (512) 555-0142',
    status: 'driving',
    vehicleId: 'VEH-001',
    currentLocation: { lat: 32.7767, lng: -96.797, city: 'Dallas', state: 'TX' },
    hos: {
      drivingRemaining: 6.5,
      onDutyRemaining: 8.0,
      drivingToday: 4.5,
      onDutyToday: 6.0,
      sleeperToday: 0,
      offDutyToday: 2.0,
      hasViolation: false,
      cycleUsed: 42.5,
      cycleRemaining: 27.5,
    },
    etaNextStop: '2:45 PM',
    currentLoad: 'LOAD-8821',
    milesDrivenToday: 287,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-002',
    name: 'Sarah Chen',
    initials: 'SC',
    licenseNumber: 'CDL-CA-7734521',
    phone: '+1 (213) 555-0198',
    status: 'driving',
    vehicleId: 'VEH-002',
    currentLocation: { lat: 34.0522, lng: -118.2437, city: 'Los Angeles', state: 'CA' },
    hos: {
      drivingRemaining: 9.0,
      onDutyRemaining: 11.5,
      drivingToday: 2.0,
      onDutyToday: 2.5,
      sleeperToday: 8.0,
      offDutyToday: 1.5,
      hasViolation: false,
      cycleUsed: 28.0,
      cycleRemaining: 42.0,
    },
    etaNextStop: '4:15 PM',
    currentLoad: 'LOAD-8834',
    milesDrivenToday: 143,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-003',
    name: 'Robert Torres',
    initials: 'RT',
    licenseNumber: 'CDL-FL-2298341',
    phone: '+1 (305) 555-0167',
    status: 'idle',
    vehicleId: 'VEH-003',
    currentLocation: { lat: 25.7617, lng: -80.1918, city: 'Miami', state: 'FL' },
    hos: {
      drivingRemaining: 11.0,
      onDutyRemaining: 14.0,
      drivingToday: 0,
      onDutyToday: 0,
      sleeperToday: 0,
      offDutyToday: 10.0,
      hasViolation: false,
      cycleUsed: 15.0,
      cycleRemaining: 55.0,
    },
    etaNextStop: undefined,
    currentLoad: undefined,
    milesDrivenToday: 0,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-004',
    name: 'Amanda Williams',
    initials: 'AW',
    licenseNumber: 'CDL-IL-5512847',
    phone: '+1 (312) 555-0223',
    status: 'driving',
    vehicleId: 'VEH-004',
    currentLocation: { lat: 41.8781, lng: -87.6298, city: 'Chicago', state: 'IL' },
    hos: {
      drivingRemaining: 1.5,
      onDutyRemaining: 2.0,
      drivingToday: 9.5,
      onDutyToday: 12.0,
      sleeperToday: 0,
      offDutyToday: 2.0,
      hasViolation: false,
      cycleUsed: 68.0,
      cycleRemaining: 2.0,
    },
    etaNextStop: '1:30 PM',
    currentLoad: 'LOAD-8819',
    milesDrivenToday: 612,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-005',
    name: 'Derek Okafor',
    initials: 'DO',
    licenseNumber: 'CDL-GA-8834129',
    phone: '+1 (404) 555-0089',
    status: 'alert',
    vehicleId: 'VEH-005',
    currentLocation: { lat: 33.749, lng: -84.388, city: 'Atlanta', state: 'GA' },
    hos: {
      drivingRemaining: 0,
      onDutyRemaining: 0,
      drivingToday: 11.0,
      onDutyToday: 14.0,
      sleeperToday: 0,
      offDutyToday: 0,
      hasViolation: true,
      cycleUsed: 70.0,
      cycleRemaining: 0,
    },
    etaNextStop: undefined,
    currentLoad: 'LOAD-8807',
    milesDrivenToday: 724,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-006',
    name: 'Lisa Nguyen',
    initials: 'LN',
    licenseNumber: 'CDL-WA-3341892',
    phone: '+1 (206) 555-0311',
    status: 'sleeper',
    vehicleId: 'VEH-006',
    currentLocation: { lat: 47.6062, lng: -122.3321, city: 'Seattle', state: 'WA' },
    hos: {
      drivingRemaining: 11.0,
      onDutyRemaining: 14.0,
      drivingToday: 0,
      onDutyToday: 0,
      sleeperToday: 6.0,
      offDutyToday: 0,
      hasViolation: false,
      cycleUsed: 52.0,
      cycleRemaining: 18.0,
    },
    etaNextStop: '6:00 AM',
    currentLoad: 'LOAD-8841',
    milesDrivenToday: 0,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-007',
    name: 'James Patel',
    initials: 'JP',
    licenseNumber: 'CDL-AZ-9921034',
    phone: '+1 (602) 555-0445',
    status: 'driving',
    vehicleId: 'VEH-007',
    currentLocation: { lat: 33.4484, lng: -112.074, city: 'Phoenix', state: 'AZ' },
    hos: {
      drivingRemaining: 7.5,
      onDutyRemaining: 9.0,
      drivingToday: 3.5,
      onDutyToday: 5.0,
      sleeperToday: 0,
      offDutyToday: 3.0,
      hasViolation: false,
      cycleUsed: 38.5,
      cycleRemaining: 31.5,
    },
    etaNextStop: '3:00 PM',
    currentLoad: 'LOAD-8852',
    milesDrivenToday: 231,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-008',
    name: 'Tanya Brooks',
    initials: 'TB',
    licenseNumber: 'CDL-NY-6678234',
    phone: '+1 (718) 555-0567',
    status: 'offline',
    vehicleId: 'VEH-008',
    currentLocation: { lat: 40.7128, lng: -74.006, city: 'New York', state: 'NY' },
    hos: {
      drivingRemaining: 11.0,
      onDutyRemaining: 14.0,
      drivingToday: 0,
      onDutyToday: 0,
      sleeperToday: 0,
      offDutyToday: 14.0,
      hasViolation: false,
      cycleUsed: 22.0,
      cycleRemaining: 48.0,
    },
    etaNextStop: undefined,
    currentLoad: undefined,
    milesDrivenToday: 0,
    lastUpdated: new Date(Date.now() - 3600000),
  },
  {
    id: 'DRV-009',
    name: 'Carlos Mendez',
    initials: 'CM',
    licenseNumber: 'CDL-TX-1123456',
    phone: '+1 (713) 555-0789',
    status: 'driving',
    vehicleId: 'VEH-009',
    currentLocation: { lat: 29.7604, lng: -95.3698, city: 'Houston', state: 'TX' },
    hos: {
      drivingRemaining: 5.0,
      onDutyRemaining: 6.5,
      drivingToday: 6.0,
      onDutyToday: 7.5,
      sleeperToday: 0,
      offDutyToday: 2.5,
      hasViolation: false,
      cycleUsed: 55.0,
      cycleRemaining: 15.0,
    },
    etaNextStop: '5:30 PM',
    currentLoad: 'LOAD-8863',
    milesDrivenToday: 389,
    lastUpdated: new Date(),
  },
  {
    id: 'DRV-010',
    name: 'Rachel Kim',
    initials: 'RK',
    licenseNumber: 'CDL-CO-4456789',
    phone: '+1 (720) 555-0234',
    status: 'idle',
    vehicleId: 'VEH-010',
    currentLocation: { lat: 39.7392, lng: -104.9903, city: 'Denver', state: 'CO' },
    hos: {
      drivingRemaining: 8.0,
      onDutyRemaining: 10.0,
      drivingToday: 3.0,
      onDutyToday: 4.0,
      sleeperToday: 0,
      offDutyToday: 4.0,
      hasViolation: false,
      cycleUsed: 31.0,
      cycleRemaining: 39.0,
    },
    etaNextStop: undefined,
    currentLoad: undefined,
    milesDrivenToday: 198,
    lastUpdated: new Date(),
  },
]

const mockVehicles: Vehicle[] = mockDrivers.map((d, i) => ({
  id: d.vehicleId,
  make: ['Freightliner', 'Kenworth', 'Peterbilt', 'Volvo', 'Mack'][i % 5]!,
  model: ['Cascadia', 'T680', '579', 'VNL 860', 'Anthem'][i % 5]!,
  year: 2020 + (i % 4),
  vin: `1FUJGBDV${String(i + 1).padStart(2, '0')}LJK${String(10000 + i * 1234)}`,
  licensePlate: `${['TX', 'CA', 'FL', 'IL', 'GA', 'WA', 'AZ', 'NY', 'TX', 'CO'][i]}-${String(100000 + i * 12345).slice(0, 6)}`,
  status: d.status === 'driving' ? 'active' : d.status === 'offline' ? 'offline' : 'idle',
  mileage: 85000 + i * 12500,
  fuelLevel: 20 + ((i * 17) % 80),
  driverId: d.id,
  lastInspection: new Date(Date.now() - (i + 1) * 7 * 24 * 3600000),
}))

export function useFleetData() {
  const drivers = ref<Driver[]>(mockDrivers)
  const vehicles = ref<Vehicle[]>(mockVehicles)
  const loading = ref(false)

  const fleetStatus = computed<FleetStatusCount>(() => {
    const counts = { driving: 0, idle: 0, offline: 0, alert: 0, total: drivers.value.length }
    for (const d of drivers.value) {
      if (d.status === 'driving') counts.driving++
      else if (d.status === 'idle' || d.status === 'sleeper') counts.idle++
      else if (d.status === 'offline') counts.offline++
      else if (d.status === 'alert') counts.alert++
    }
    return counts
  })

  async function refresh() {
    loading.value = true
    await new Promise((r) => setTimeout(r, 800))
    loading.value = false
  }

  return { drivers, vehicles, fleetStatus, loading, refresh }
}
